[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
aibet = "2zdSF8zfWrpaNEFTnpSPwbHmuGfFpY7jsSoRYeKeDetf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./wallets/mainnet_wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
